apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: lcp-exporter-secret
spec:
  secretStoreRef:
    name: gcp-secret-store
    kind: SecretStore
  target:
    name: lcp-exporter-secret
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: {{ .Values.googleSecretManager.secretName }}
        version: {{ .Values.googleSecretManager.version }}
