{{- if not .Values.existingSecret.name -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lcp-exporter.secretName" . }}
  {{- if .Values.secret.annotations }}
  annotations:
    {{- toYaml .Values.secret.annotations | nindent 4 }}
  {{- end }}
  labels:
    {{- include "lcp-exporter.labels" . | nindent 4 }}
type: Opaque
data:
  lcpApiToken: {{ .Values.lcp.apiToken | b64enc }}
{{- end }}
