{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "lcp-exporter.labels" . | nindent 4 }}
  name: {{ template "lcp-exporter.serviceAccountName" . }}
  {{- if .Values.serviceAccount.annotations }}
  annotations:
  {{ toYaml .Values.serviceAccount.annotations | indent 4 }}
  {{- end }}
{{- end }}
