name: release
on:
  push:
    branches:
      - master
    paths:
      - 'Dockerfile'
      - '**/*.go'
      - 'chart/lcp-exporter/**/*.yaml'
      - '.github/workflows/**.yml'
jobs:
  image:
    name: Release Docker image and Helm Chart
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      REGISTRY: ghcr.io
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Extract repo name
        run: echo "REPO_NAME=${GITHUB_REPOSITORY##*/}" >> $GITHUB_ENV
      - name: Extract current version from VERSION
        run: echo "VERSION=$(sed -e 's,.*/\(.*\),\1,;s/-snapshot$//' VERSION)" >> "$GITHUB_ENV"
      - name: Setup
        uses: docker/setup-buildx-action@v3
      - name: QEMU
        uses: docker/setup-qemu-action@v3
      - name: Login
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Buildx Multi-platform Linux Docker Images
        id: docker-build-push-multi-platform
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64
          file: ./Dockerfile
          build-args: VERSION=${{ env.VERSION }}
          tags: ${{ env.REGISTRY }}/${{ github.repository }}:${{ env.VERSION }}
          push: true
          outputs: type=image,name=target
      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
      - name: Bump Chart.yaml version
        uses: mikefarah/yq@master
        with:
          cmd: yq -i '.version = strenv(VERSION) | .appVersion = "v"+strenv(VERSION)' ./chart/${{ env.REPO_NAME }}/Chart.yaml
        env:
          VERSION: ${{ env.VERSION }}
      - name: Run helm-docs
        uses: losisin/helm-docs-github-action@v1
      - name: Set next snapshot version
        run: |
          git pull origin master
          IFS='.' read -r major minor patch <<< "${{ env.VERSION }}"
          new_version="${major}.${minor}.$((patch+1))-snapshot"
          echo $new_version > VERSION.tmp && mv VERSION.tmp VERSION
          git commit -am "chore: bump version to ${new_version}"
          git push origin master
      - name: Publish Helm chart
        uses: helm/chart-releaser-action@v1.7.0
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          charts_dir: chart
          skip_existing: true
